---
title: STECF data download and inspect (part_1)
author: Robert P. McGuinn
date: '2019-12-21'
slug: stecf-data-download-and-exploration
categories: []
tags: []
---



<div id="purpose" class="section level1">
<h1>purpose</h1>
<p>Download and take an intial look at the European Commisson,Fisheries and Aquaculture: Scientific, Technical and Economic Committee for Fisheries (STECF) aquaculture economic data tables.</p>
</div>
<div id="analyst-note" class="section level1">
<h1>analyst note</h1>
<p>This is part 1. As I move through the stages of exploration, and when I feel like it might be worth sharing with you, I’ll post another part. Each part will include data and package load steps, so that they can be more stand-alone.</p>
</div>
<div id="data-description" class="section level1">
<h1>data description</h1>
<p>Agency: European Commisson,Fisheries and Aquaculture.</p>
<p><a href="https://stecf.jrc.ec.europa.eu/dd/aqua" class="uri">https://stecf.jrc.ec.europa.eu/dd/aqua</a></p>
</div>
<div id="download-data" class="section level1">
<h1>download data</h1>
<p><a href="https://stecf.jrc.ec.europa.eu/documents/43805/2192243/STECF+18-19+-+Aquaculture+economic+data+tables.xlsx/bbbefd1b-62ca-45bd-a632-cfb97bd0e2ef" class="uri">https://stecf.jrc.ec.europa.eu/documents/43805/2192243/STECF+18-19+-+Aquaculture+economic+data+tables.xlsx/bbbefd1b-62ca-45bd-a632-cfb97bd0e2ef</a></p>
</div>
<div id="original-file-format" class="section level1">
<h1>original file format</h1>
<p>Excel spreadsheet(*.xlsx)</p>
</div>
<div id="original-file-name" class="section level1">
<h1>original file name</h1>
<ul>
<li>‘STECF 18-19 - Aquaculture economic data tables.xlsx’</li>
</ul>
<p>Once you have the file downloaded, open it in Excel and take a look. I see that sheets 5 and sheets 6 are the ‘DCF data’ and the ‘EUMAP data’ respectively. So go about uploading those two tables in R.</p>
</div>
<div id="load-packages" class="section level1">
<h1>load packages</h1>
<p>The following list of packages are required to run the subsequent R commands. Install these if you do not already have them.</p>
<pre class="r"><code>library(openxlsx)
library(tidyverse)
library(magrittr)</code></pre>
</div>
<div id="load-data-to-r" class="section level1">
<h1>load data to R</h1>
<pre class="r"><code># load the data 
setwd(&quot;C:/rworking/fish.farmr/indata&quot;)

dcf &lt;- read.xlsx(&quot;C:/rworking/fish.farmR/indata/STECF 18-19 - Aquaculture economic data tables.xlsx&quot;, sheet = 5, colNames = TRUE)

eumap &lt;- read.xlsx(&quot;C:/rworking/fish.farmR/indata/STECF 18-19 - Aquaculture economic data tables.xlsx&quot;, sheet = 6, colNames = TRUE)</code></pre>
<p>Now you have <strong>‘dcf’</strong> and <strong>‘eumap’</strong> data frames.</p>
</div>
<div id="check-the-data-frame-size-and-variable-names" class="section level1">
<h1>check the data frame size and variable names</h1>
<p>Run the following exploratory commands.</p>
<pre class="r"><code># look and variables and df size
names(dcf)</code></pre>
<pre><code>##  [1] &quot;country_code&quot;      &quot;country_name&quot;      &quot;species&quot;          
##  [4] &quot;common_name&quot;       &quot;scientific_name&quot;   &quot;variable_group&quot;   
##  [7] &quot;variable_code&quot;     &quot;variable_name&quot;     &quot;environment&quot;      
## [10] &quot;environment_hn&quot;    &quot;segment_code&quot;      &quot;segment_name&quot;     
## [13] &quot;value&quot;             &quot;unit&quot;              &quot;year&quot;             
## [16] &quot;sample&quot;            &quot;population&quot;        &quot;sample_rate&quot;      
## [19] &quot;sampling_strategy&quot; &quot;precision_level&quot;   &quot;comments&quot;         
## [22] &quot;ordering&quot;          &quot;Regulation&quot;</code></pre>
<pre class="r"><code>length(dcf)</code></pre>
<pre><code>## [1] 23</code></pre>
<pre class="r"><code>dim(dcf)</code></pre>
<pre><code>## [1] 343498     23</code></pre>
<pre class="r"><code># look and variables and df size
names(eumap)</code></pre>
<pre><code>##  [1] &quot;country_code&quot;      &quot;country_name&quot;      &quot;species&quot;          
##  [4] &quot;common_name&quot;       &quot;scientific_name&quot;   &quot;variable_group&quot;   
##  [7] &quot;variable_code&quot;     &quot;variable_name&quot;     &quot;environment&quot;      
## [10] &quot;environment_hn&quot;    &quot;segment_code&quot;      &quot;segment_name&quot;     
## [13] &quot;value&quot;             &quot;unit&quot;              &quot;year&quot;             
## [16] &quot;sample&quot;            &quot;population&quot;        &quot;sample_rate&quot;      
## [19] &quot;sampling_strategy&quot; &quot;precision_level&quot;   &quot;comments&quot;         
## [22] &quot;ordering&quot;          &quot;Regulation&quot;</code></pre>
<pre class="r"><code>length(eumap)</code></pre>
<pre><code>## [1] 23</code></pre>
<pre class="r"><code>dim(eumap)</code></pre>
<pre><code>## [1] 111438     23</code></pre>
<pre class="r"><code># check for variable name mismatches
setdiff(names(dcf), names(eumap))</code></pre>
<pre><code>## character(0)</code></pre>
<pre class="r"><code>setdiff(names(eumap), names(dcf))</code></pre>
<pre><code>## character(0)</code></pre>
<p>Running the commands above will give you a good idea of the data structure and size.</p>
</div>
<div id="now-you-can-play" class="section level1">
<h1>now you can play!</h1>
<p>First, generate some stats of interest. These will then be available for placing in-line with your text descriptions of the data frames.</p>
<pre class="r"><code># number of records (dcf)
a &lt;- length(dcf$country_code) 

# number of unique species(dcf)
b &lt;- length(levels(factor(dcf$species)))

# number of records(eumap)
c &lt;-  length(eumap$country_code)

# number of unique species(eumap)
d &lt;- length(levels(factor(eumap$species)))</code></pre>
<p>The number of records within <strong>‘dcf’</strong> is 343,498, with 164 unique species, while the number of records within <strong>‘eumap’</strong> are 111,438, with 74 unique ‘species’.</p>
</div>
<div id="write-inline-code" class="section level1">
<h1>write inline code</h1>
<p>The above paragraph uses inline code for the numerical values. Example below of what would be placed in an RMarkdown document, like this one.</p>
<pre class="r"><code>...number of records within dcf is `r prettyNum(a, big.mark = &quot;,&quot;)`</code></pre>
</div>
